### PR TITLE
Update spectatorCount.nut

### PR DESCRIPTION
**Pull request by AmazingDM**
fix error

### CODE REVIEW

**Comment by wubushanyan** [comment]
This pull did fix and let me successfully enter the game,
But do u have encountered a phenomenon where the localplayer approached the rope and caused the game to crash
I see the crash log like this:
```
(steam:4002): LIBDBUSMENU-GLIB-WARNING **: 23:06:38.041: Trying to remove a child that doesn't believe we're it's parent.

(steam:4002): LIBDBUSMENU-GLIB-WARNING **: 23:06:38.048: Trying to remove a child that doesn't believe we're it's parent.

(steam:4002): LIBDBUSMENU-GLIB-WARNING **: 23:06:38.048: Trying to remove a child that doesn't believe we're it's parent.

(steam:4002): LIBDBUSMENU-GLIB-WARNING **: 23:06:38.048: Trying to remove a child that doesn't believe we're it's parent.

(steam:4002): LIBDBUSMENU-GLIB-WARNING **: 23:06:38.048: Trying to remove a child that doesn't believe we're it's parent.

(steam:4002): LIBDBUSMENU-GLIB-WARNING **: 23:06:38.048: Trying to remove a child that doesn't believe we're it's parent.

(steam:4002): LIBDBUSMENU-GLIB-WARNING **: 23:06:38.048: Trying to remove a child that doesn't believe we're it's parent.

(steam:4002): LIBDBUSMENU-GLIB-WARNING **: 23:06:38.048: Trying to remove a child that doesn't believe we're it's parent.

(steam:4002): LIBDBUSMENU-GLIB-WARNING **: 23:06:38.048: Trying to remove a child that doesn't believe we're it's parent.

(steam:4002): LIBDBUSMENU-GLIB-WARNING **: 23:06:38.048: Trying to remove a child that doesn't believe we're it's parent.

(steam:4002): LIBDBUSMENU-GLIB-WARNING **: 23:06:38.048: Trying to remove a child that doesn't believe we're it's parent.

(steam:4002): LIBDBUSMENU-GLIB-WARNING **: 23:06:38.048: Trying to remove a child that doesn't believe we're it's parent.

(process:8749): GLib-GObject-CRITICAL **: 23:06:41.626: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
```

**Comment by RickIsNotMyRealName** [comment]
where did u get this log from?

**Review by RickIsNotMyRealName — APPROVED** [review]

**Comment by wubushanyan** [comment]
> where did u get this log from?

Using the terminal to open Steam, you can see the logs in the process of Steam running, including some logs in the process of Apex Legends, but they may not be detailed. The detailed content needs to be viewed in the crash dump

The dump package is located in the "Crashpd" folder under the Apex legends folder, but I dont have tool to view it


PS:
I still have a problem with players approaching the rope and then the game crashes,I tested remove the spectatorscount from VPK then it works fine

**Comment by RickIsNotMyRealName** [comment]
ok i haven't used the script in a while but i have another person using it and they are reporting an issue like this as well im currently rewriting my script loader but will update here once i find the issue. also im on ea desktop and i dont have that crashpd folder

**Pull request merged**
